### ISSUE TITLE
404 for _next/static assets when split to variant

### ISSUE THREAD

**Issue by curiousercreative** [aiji42/next-with-split#138]
Many static chunks are failing to load when traffic is split to the variant. Curiously, many static chunks are loading just fine at the same time. If I had to guess, next-with-split is not splitting traffic for these static requests and we're loading a client application from the variant and then requesting assets from the original. Unfortunately, I don't have public code to share for reproduction at the moment.

```
/_next/static/chunks/pages/_app-a7bb2c13a9610808.js net::ERR_ABORTED 404
/_next/static/chunks/pages/index-8bca188dacdd485a.js net::ERR_ABORTED 404
/_next/static/9XvUc6UIlw_bO83eYBxy-/_middlewareManifest.js net::ERR_ABORTED 404
/_next/static/chunks/pages/_app-a7bb2c13a9610808.js net::ERR_ABORTED 404
/_next/static/9XvUc6UIlw_bO83eYBxy-/_ssgManifest.js net::ERR_ABORTED 404
```

**Comment by aiji42** [comment]
Access to paths such as `/_next/static/` and `/_next/data`, which are proprietary by default to Next.js, do not pass through the middleware and cannot be handled by this library.
Only `/_next/static/` can be changed by `assetPrefix` in `next.config.js`. This library adds a host to the `assetPrefix` on the challenger side, so that the browser can directly request assets from the challenger's server without going through the original server. https://github.com/aiji42/next-with-split/blob/main/src/with-split.ts#L55


This is why you have to import `next-with-split` into `next.config.js` not only for the original but also for the challenger. Please check once again that `next-with-split` is imported into Challenger's `next.config.js` in your problematic deployment. 

Note that there is no way to change this for `/_next/data`, and furthermore, we can't handle it because it doesn't pass through the middleware. Fortunately, this path is only used for pre-fetching, so even if access to this path results in a 404, it is not a fatal problem.

**Comment by curiousercreative** [comment]
Yep, I wasn't receiving a `process.env.VERCEL_URL` because I hadn't enabled ["expose system environment variables" ](https://github.com/vercel/next.js/discussions/15902#discussioncomment-348992). Because the default deploy URL doesn't match custom domains set (or git branch deploy templating), I found that setting the `hostname` configuration option will be a better option.
